### ISSUE TITLE
13: Implementation of Rich text box type form element

### ISSUE THREAD

**Issue by kiranharidas187** [ELEVATE-Project/frontend-utils-library#16]
## Description
Implement the Rich text box type form type in the dynamic form. All the configurations (placeholder, validation, layout, etc) required for the rendering of the rating type form should be configurable using JSON.

## Goals
- [ ] Create an interface for the base form object.
- [ ] Install angular material as the dependency for the library
- [ ] As per the reference implementation, convert the code to handle the angular material input component.
- [ ] Implement the test cases for the component
- [ ] Prepare proper documentation for the implementation

## Acceptance Criteria
- [ ] Should be able to render the form with a  Rich text box type form element

## Implementation Details
Angular, HTML, CSS

## Mockups / Wireframes
All the forms can be viewed in [this](https://mentored.shikshalokam.org/) portal

### Product Name
SL-Library

### Project Name
SL-Library

### Organization Name:
Shikshalokam

### Domain
Education

### Tech Skills Needed:
Angular, HTML, CSS

### Mentor(s)
Amoghavarsh

### Complexity
Medium

### Category
Features

### Sub Category
Frontend, Library

**Comment by nikhil061102** [comment]
Sir, I am interested and have some doubts. 
1. Are external libraries and packages allowed ?
2. How should it look (are there any UI designs/patterns)
Please let me know.

**Comment by vsvishalsharma** [comment]
@kiranharidas187 Iwould love to work on this issue

**Comment by sid-nc** [comment]
@kiranharidas187 Can I get assigned to this issue

**Comment by Yash-Sajwan24** [comment]
@kiranharidas187 I understand the problem, and I believe I have the necessary skills. Could I have the opportunity to work on this?

**Comment by sahil-1729** [comment]
@kiranharidas187 I would like to work on this issue

**Comment by aishalxgupta** [comment]
Hey @kiranharidas187, I have previous experience working with HTML, CSS and Angular and would look really forward to being assigned this issue.

**Comment by Sohajawdekar** [comment]
Hey @kiranharidas187 , I have worked with HTML, CSS and Angular. Could you please assign me this issue ?

**Comment by kpratham351** [comment]
hello @kiranharidas187 i want to work on this issue

**Comment by utkarsh4321** [comment]
@kiranharidas187 I am interested in this issue. Can we talk on this?

**Comment by Priyanshu-bansal** [comment]
Hello sir, @kiranharidas187 , I am really interested in this issue and would like to contribute towards it. Can you assign me this issue?

looking forward to work on this, Thank you!!

**Comment by harshilshah99** [comment]
@kiranharidas187 I have raised a PR for the above issue kindly review it

**Comment by Vinod-V3** [comment]
Hello everyone,
Those who all are interested to work in this project/issue can join this discord channel ( [link](https://discord.com/invite/RbQzUCb7) ), where we will be discussing and resolving the queries related to this project.
Before starting please go through this [document](https://docs.google.com/document/d/1F5POeU4DLMOO-mDC7Da5YKVXdS55sIL2IIzLPveXcE4/edit) and [video](https://drive.google.com/file/d/1tU8Jq80Jho1XmRBESALToQq8ROjJSsD1/view?usp=sharing) so that you all will get a basic understanding on the project and also the initial setup for this project.

**Comment by LavanyaaCSE** [comment]
Hello @kiranharidas187 ,
I am interested in working on this issue; could you please assign it to me? I have prior experience working with HTML, CSS and Angular. It would be a great opportunity for me to contribute to this issue. Can you please assign me a task

**Comment by ghost** [comment]
Hlo myself Rishita i want work on this issue.

**Comment by PayalKumari10** [comment]
Hi @kiranharidas187  

I'd like to contribute to this issue. My plan includes:
1. Creating an interface for the base form object.
2. Installing Angular Material.
3. Converting code to handle Angular Material's rich text box component with JSON-configurable options.
4. Implementing test cases.
5. Preparing detailed documentation.
Please let me know if there are any specific requirements. I look forward to contributing!

Thank you

**Comment by arghaDEVIL** [comment]
@kiranharidas187 please assign this issue to me

**Comment by VedantKhairnar** [comment]
Hello @PayalKumari10 
Are you still interested in working on the issue?

If yes, @kiranharidas187 
Will you pls assign it to her?

Thanks.

**Comment by PayalKumari10** [comment]
yes @VedantKhairnar , I am interested in working on this.

**Comment by VedantKhairnar** [comment]
Hello @PayalKumari10 
Pls directly raise the PR. Just give us an indication that you are working on it. Thanks.

**Comment by debangi29** [comment]
May I work on this issue? @VedantKhairnar

**Comment by PayalKumari10** [comment]
> Hello @PayalKumari10 Pls directly raise the PR. Just give us an indication that you are working on it. Thanks.

Thank you for the update. I've already started working on the issue and will raise the draft PR shortly. I'll keep you posted on the progress. Thanks @VedantKhairnar  sir

**Comment by VedantKhairnar** [comment]
Hello @debangi29 
Payal is already working on the issue.
You may check other issues [here](https://www.codeforgovtech.in/community-program-projects/).
Let me know if you face difficulty finding one.
Thanks.

**Comment by VedantKhairnar** [comment]
Hello @PayalKumari10 
Any update on the contribution?
Please let us know if you face any issues.
Thanks.

**Comment by SGCODEX** [comment]
Can this issue be assigned to me?

**Comment by HasanZaigam** [comment]
hey, i want to contribute to this project from her I can start to contribute in project

**Comment by NishchayRajput** [comment]
Hey @kiranharidas187 ,
 I am interested to work on this can you assign me.

**Comment by sanjayselvamj** [comment]
Hey @kiranharidas187,  

I have worked on a similar project before and would like to take this further.  
Can you assign it to me so I can make it my own and enhance it?  

Looking forward to your response.  

Best,  
@sanjayselvamj

**Comment by EthicSpectra** [comment]
> Sir, I am interested and have some doubts.
> 
> 1. Are external libraries and packages allowed ?
> 2. How should it look (are there any UI designs/patterns)
>    Please let me know.

I request to work on implementing the Rich Text Box form type in the dynamic form for the SL-Library project. Please provide the necessary details to proceed.

**Comment by EthicSpectra** [comment]
Hey @kiranharidas187,

I’m excited about the opportunity to contribute to this feature! Having worked on similar implementations, I’d love to take ownership of this and bring the Rich Text Box form type to life.

Let me know if I can take it forward!

Best,
[@EthicSpectra](https://github.com/EthicSpectra)

**Comment by 0xEth1cX** [comment]
Hey @kiranharidas187,

I hope you're doing well. I have experience working on similar implementations and would love the opportunity to contribute to this feature. I believe I can add value by ensuring a well-structured and configurable Rich Text Box form type.

Please let me know if I can take this forward. Looking forward to your response.

Best regards,
[@EthicSpectra](https://github.com/EthicSpectra)

**Comment by AyushRaj0128** [comment]
```
Excited to contribute! I'll implement the Rich text box form type with JSON configuration, focusing on:

- Defining a base form object interface.
- Integrating Angular Material (or a suitable rich text editor component).
- Handling JSON configurations (placeholder, validation, layout, etc.).
- Implementing the Rich text box component.
- Writing comprehensive unit tests.
- Providing clear documentation.

Looking forward to working on this!
```

**Comment by biswajit-sarkar-007** [comment]
@kiranharidas187, I am interested in working on this issue and would be delighted to contribute to this project. For this issue, it seems you want to develop a dynamic form element with a rich text box type functionality.

this is how i want to processed this work : 
1.Create a reusable Rich Text Box component

2.Integrate a rich text editor (like ngx-editor or Quill) within Angular

3.Use Angular Material to wrap the editor inside a mat-form-field for consistent styling

4.Accept JSON configuration for:

                                                  Placeholder text

                                                  Validation (e.g., required)

                                                  Layout options.
{
  "type": "rich-text",
  "placeholder": "Describe your experience",
  "validation": {
    "required": true
  }
}


5.Render the field dynamically as part of the form builder.

6.Write test cases to ensure the component renders and validates as expected.

7.Add documentation on how to use the Rich Text Box in the form config


###  This is I intend to approach this work. If I encounter any issues while this problem, I will make adjustments as necessary.

**Comment by Piyush0000** [comment]
@kiranharidas187 , assign me this issue

**Comment by Richajaishwal0** [comment]
Hi @kiranharidas187 
I would like to express my interest in working on this issue. I have carefully reviewed the requirements and would be happy to contribute to the SL-Library project.

### Implementation Plan:
- **Interface**: I will create a configurable interface for the rich text box form type, allowing properties like `placeholder`, `label`, `formControlName`, `validation`, and `layout` to be defined through JSON.
- **Angular Material Integration**: I will integrate Angular Material components for rendering the rich text box (using `mat-form-field` and possibly `ngx-quill` or a suitable content-editable wrapper).
- **Dynamic Rendering**: The dynamic form will be updated to support the new `"rich-text"` type based on the JSON schema.
- **Validation & Layout**: I will ensure support for validations (e.g., required, minLength) and grid-based layout.
- **Testing**: I will implement unit tests to validate rendering, form control behavior, and error handling.
- **Documentation**: I will provide proper documentation with configuration examples and usage guidelines for future reference.

Here is an example of the intended JSON configuration:
```json
{
  "type": "rich-text",
  "label": "Description",
  "placeholder": "Enter detailed description here...",
  "formControlName": "description",
  "validation": {
    "required": true,
    "minLength": 10
  },
  "layout": {
    "row": 2,
    "col": 12
  }
}
```
Please let me know if you would be able to assign this to me. I’m excited to contribute and ensure the solution aligns with the project’s goals and standards.

[Richajaishwal](https://github.com/Richajaishwal0)

**Comment by tusharshah21** [comment]
Hi @kiranharidas187 ,

I'd love to take this up! I have hands-on experience with Angular, dynamic forms, and Angular Material. Confident in implementing the rich text box with full JSON config support, tests, and clean documentation.

Looking forward to your approval!

**Comment by Jaysinh146** [comment]
Hi there,

I'm really interested in this issue! I've worked on similar Angular components before, and I'm excited about the opportunity to implement a configurable Rich Text Box type in the dynamic form. I'm confident that my experience with Angular, HTML, and CSS, along with my familiarity with Angular Material, will allow me to contribute effectively. I'm looking forward to setting up the base form interface, integrating the Angular Material input components, and writing comprehensive tests and documentation for the component. I'm excited to collaborate with the team and learn from @Amoghavarsh. Please let me know how I can help get this feature underway!

Thanks,
Jaysinh

**Comment by SrushtiPatil-tech** [comment]
@kiranharidas187 
I would like to work on this issue. Please assign it to me.

**Comment by CoDIngDEMon018** [comment]
@kiranharidas187 
I would like to work on this issue. Please assign it to me.

**Comment by kiranharidas187** [comment]
Hi everyone. 

This fix is no longer required. Hence closing it
